name: Master Branch
on:
  push:
    branches:
      - 'feature/test_github_action'
jobs:
  test:
    name: Unit-Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Test with Gradle
        run: ./gradlew test
  docker:
    name: Publish Docker Image
    runs-on: ubuntu-latest
    env:
      REPO: ${{ secrets.DOCKER_REPO }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: debug
        run: echo $DOCKER_USERNAME && echo $REPO  
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: nhuthm080280/crypto-history:latest